spring:
  application:
    name: neo4j-demo
  neo4j:
    uri: neo4j://10.185.244.152:27687
    authentication:
      username: neo4j
      password: neo4jvciso
  data:
    neo4j:
      database: asset251212
